console.log('assets working');
var deckOfCards = [
 { name: 'Ace', value : 1, suit: 'clubs' },
 { name: '2', value : 2, suit: 'clubs' },
 { name: '3', value: 3, suit: 'clubs' },
 { name: '4', value: 4 , suit: 'clubs' },
 { name: '5', value: 5, suit: 'clubs' },
 { name: '6', value: 6, suit: 'clubs' },
 { name: '7', value: 7, suit: 'clubs' },
 { name: '8', value: 8, suit: 'clubs' },
 { name: '9', value: 9, suit: 'clubs' },
 { name: '10', value: 10, suit: 'clubs' },
 { name: 'Jack', value: 10, suit: 'clubs' },
 { name: 'Queen', value: 10, suit: 'clubs' },
 { name: 'King', value: 10, suit: 'clubs' },
 { name: 'Ace', value : 1, suit: 'diamonds' },
 { name: '2', value : 2, suit: 'diamonds' },
 { name: '3', value: 3, suit: 'diamonds' },
 { name: '4', value: 4 , suit: 'diamonds' },
 { name: '5', value: 5, suit: 'diamonds' },
 { name: '6', value: 6, suit: 'diamonds' },
 { name: '7', value: 7, suit: 'diamonds' },
 { name: '8', value: 8, suit: 'diamonds' },
 { name: '9', value: 9, suit: 'diamonds' },
 { name: '10', value: 10, suit: 'diamonds' },
 { name: 'Jack', value: 10, suit: 'diamonds' },
 { name: 'Queen', value: 10, suit: 'diamonds' },
 { name: 'King', value: 10, suit: 'diamonds' },
 { name: 'Ace', value : 1, suit: 'hearts' },
 { name: '2', value : 2, suit: 'hearts' },
 { name: '3', value: 3, suit: 'hearts' },
 { name: '4', value: 4 , suit: 'hearts' },
 { name: '5', value: 5, suit: 'hearts' },
 { name: '6', value: 6, suit: 'hearts' },
 { name: '7', value: 7, suit: 'hearts' },
 { name: '8', value: 8, suit: 'hearts' },
 { name: '9', value: 9, suit: 'hearts' },
 { name: '10', value: 10, suit: 'hearts' },
 { name: 'Jack', value: 10, suit: 'hearts' },
 { name: 'Queen', value: 10, suit: 'hearts' },
 { name: 'King', value: 10, suit: 'hearts' },
 { name: 'Ace', value : 1, suit: 'diamonds' },
 { name: '2', value : 2, suit: 'diamonds' },
 { name: '3', value: 3, suit: 'diamonds' },
 { name: '4', value: 4 , suit: 'diamonds' },
 { name: '5', value: 5, suit: 'diamonds' },
 { name: '6', value: 6, suit: 'diamonds' },
 { name: '7', value: 7, suit: 'diamonds' },
 { name: '8', value: 8, suit: 'diamonds' },
 { name: '9', value: 9, suit: 'diamonds' },
 { name: '10', value: 10, suit: 'diamonds' },
 { name: 'Jack', value: 10, suit: 'diamonds' },
 { name: 'Queen', value: 10, suit: 'diamonds' },
 { name: 'King', value: 10, suit: 'diamonds' }
];
